"use client";

import {FormEvent, useCallback, useEffect, useState} from "react";
import {getSupabaseBrowser} from "../../lib/supabase-browser";
import "./studio.css";
import "./moderation.css";

type Question = {id: number; question: string; context: string; created_at: string};
type Comment = {id: number; essay_slug: string; paragraph_id: string | null; display_name: string; guest_email: string | null; body: string; created_at: string; parent_id?: number | null; is_creator_reply?: boolean};

export default function Studio() {
  const [title, setTitle] = useState(""); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState("");
  const [questions, setQuestions] = useState<Question[]>([]); const [comments, setComments] = useState<Comment[]>([]); const [replies, setReplies] = useState<Record<number, string>>({});
  const [token, setToken] = useState(""); const [authorized, setAuthorized] = useState(false);

  const loadInbox = useCallback(async (accessToken: string) => {const response = await fetch("/api/creator", {headers: {authorization: `Bearer ${accessToken}`}, cache: "no-store"}); const data = await response.json(); if (response.ok) {setQuestions(data.questions || []); setComments(data.comments || []); setAuthorized(true); setMessage("");} else {setAuthorized(false); setMessage(data.error || "Creator access could not be confirmed.");}}, []);
  useEffect(() => {const supabase = getSupabaseBrowser(); if (!supabase) {setMessage("The sign-in service is temporarily unavailable."); return;} supabase.auth.getSession().then(({data}) => {const accessToken = data.session?.access_token; if (!accessToken) {setMessage("Sign in with the creator account first."); return;} setToken(accessToken); loadInbox(accessToken);});}, [loadInbox]);

  async function publish(event: FormEvent) {event.preventDefault(); if (!token || !authorized) return setMessage("Creator sign-in is required."); const form = new FormData(); form.set("title", title); if (file) form.set("file", file); const response = await fetch("/api/works", {method: "POST", headers: {authorization: `Bearer ${token}`}, body: form}); const data = await response.json(); setMessage(response.ok ? `Published. Your essay is live at /essays/${data.slug}` : data.error);}
  async function reply(comment: Comment) {const body = replies[comment.id]?.trim(); if (!body || !token) return; const response = await fetch("/api/comments", {method: "POST", headers: {"content-type": "application/json", authorization: `Bearer ${token}`}, body: JSON.stringify({essay_slug: comment.essay_slug, paragraph_id: comment.paragraph_id, parent_id: comment.id, body})}); if (response.ok) {setReplies((current) => ({...current, [comment.id]: ""})); await loadInbox(token);} else setMessage("Your reply could not be posted.");}
  async function deleteQuestion(question: Question) {if (!token || !window.confirm("Delete this question and its discussion replies?")) return; const response = await fetch(`/api/questions/${question.id}`, {method: "DELETE", headers: {authorization: `Bearer ${token}`}}); const data = await response.json(); if (response.ok) {setMessage("Question deleted."); await loadInbox(token);} else setMessage(data.error || "The question could not be deleted.");}
  async function deleteComment(comment: Comment) {if (!token || !window.confirm("Delete this comment and any replies beneath it?")) return; const response = await fetch(`/api/comments/${comment.id}`, {method: "DELETE", headers: {authorization: `Bearer ${token}`}}); const data = await response.json(); if (response.ok) {setMessage("Comment deleted."); await loadInbox(token);} else setMessage(data.error || "The comment could not be deleted.");}

  return <main className="studio"><a href="/">Back to publication</a><section><p className="eyebrow">Private newsroom</p><h1>Creator Studio</h1><p>Only <strong>brileycastille@gmail.com</strong> can publish, reply as Briley, or remove content.</p>{message && <p className="studio-message" role="status">{message}</p>}{!authorized && <p><a className="button" href="/account">Go to Creator sign in</a></p>}{authorized && <>
    <div className="studio-panel"><h2>Publish a new work</h2><form onSubmit={publish}><label>Essay title<input required value={title} onChange={(event) => setTitle(event.target.value)}/></label><label>Word document<input required type="file" accept=".docx" onChange={(event) => setFile(event.target.files?.[0] || null)}/></label><button className="button" type="submit">Publish essay</button></form></div>
    <div className="studio-panel"><h2>Standalone questions</h2>{questions.length === 0 ? <p>No reader questions yet.</p> : questions.map((question) => <article key={question.id}><small>{question.context}</small><p>{question.question}</p><button className="danger" type="button" onClick={() => deleteQuestion(question)}>Delete question</button></article>)}</div>
    <div className="studio-panel"><h2>Comments and replies</h2><p>Use Delete to remove spam, harassment, or offensive content from the public website.</p>{comments.length === 0 ? <p>No comments yet.</p> : comments.map((comment) => <article key={comment.id}><small>{comment.essay_slug}{comment.paragraph_id && comment.paragraph_id !== "end" ? ` | ${comment.paragraph_id}` : " | whole essay"}</small><h3>{comment.display_name}</h3><p>{comment.body}</p><div className="moderation-actions"><button className="danger" type="button" onClick={() => deleteComment(comment)}>Delete comment</button></div><textarea rows={3} value={replies[comment.id] || ""} onChange={(event) => setReplies((current) => ({...current, [comment.id]: event.target.value}))} placeholder="Reply as Briley"/><button type="button" onClick={() => reply(comment)}>Post creator reply</button></article>)}</div>
  </>}</section></main>;
}
